ALTER TYPE "FreelancerLeadStatus" ADD VALUE IF NOT EXISTS 'INTERESTED';
ALTER TYPE "FreelancerLeadStatus" ADD VALUE IF NOT EXISTS 'DEMO_SCHEDULED';
ALTER TYPE "FreelancerLeadStatus" ADD VALUE IF NOT EXISTS 'NEGOTIATION';
ALTER TYPE "FreelancerLeadStatus" ADD VALUE IF NOT EXISTS 'ONBOARDED';
