// Tire size data for programmatic SEO pages
// Each tire size gets a unique /reifen/[size] page
// URL pattern: /reifen/205-55-r16

export interface TireSizeData {
  slug: string
  width: number
  aspectRatio: number
  rimDiameter: number
  displayName: string
  category: string
  commonVehicles: string[]
  speedIndices: string[]
  loadIndices: string[]
  seasonTip: string
  monthlySearchVolume: number
  metaTitle: string
  metaDescription: string
  h1: string
  introText: string
}

const CATEGORY_KLEINWAGEN = 'Kleinwagen'
const CATEGORY_KOMPAKT = 'Kompaktklasse'
const CATEGORY_MITTELKLASSE = 'Mittelklasse'
const CATEGORY_OBERKLASSE = 'Oberklasse'
const CATEGORY_SUV = 'SUV / Geländewagen'
const CATEGORY_SPORT = 'Sportwagen / Performance'
const CATEGORY_TRANSPORTER = 'Transporter / Van'

function makeTitle(display: string): string {
  return `${display} Reifen günstig kaufen & montieren | Bereifung24`
}

function makeDescription(display: string, vehicles: string[]): string {
  const vehicleStr = vehicles.slice(0, 3).join(', ')
  return `${display} Reifen online bestellen mit Montage-Service. Passend für ${vehicleStr} u.v.m. ✓ Bestpreisgarantie ✓ Professionelle Montage ✓ Reifen direkt zur Werkstatt geliefert.`
}

function makeH1(display: string): string {
  return `${display} Reifen kaufen mit Montage`
}

function makeIntro(display: string, category: string, vehicles: string[]): string {
  const vehicleStr = vehicles.slice(0, 4).join(', ')
  return `Die Reifengröße ${display} gehört zu den beliebtesten Größen im Bereich ${category}. Sie wird unter anderem bei ${vehicleStr} und vielen weiteren Modellen verbaut. Bei Bereifung24 findest du ${display} Reifen von Top-Marken zum besten Preis – inklusive professioneller Montage in einer Partnerwerkstatt in deiner Nähe.`
}

export const TIRE_SIZES: TireSizeData[] = [
  // === KLEINWAGEN ===
  {
    slug: '155-65-r14',
    width: 155, aspectRatio: 65, rimDiameter: 14,
    displayName: '155/65 R14',
    category: CATEGORY_KLEINWAGEN,
    commonVehicles: ['VW Up', 'Skoda Citigo', 'Seat Mii', 'Fiat 500', 'Toyota Aygo'],
    speedIndices: ['T', 'H'], loadIndices: ['75'],
    seasonTip: 'Für Stadtfahrten ideal als Ganzjahresreifen, für häufige Autobahnfahrten separate Sommer- und Winterreifen empfohlen.',
    monthlySearchVolume: 4800,
    metaTitle: makeTitle('155/65 R14'), metaDescription: makeDescription('155/65 R14', ['VW Up', 'Fiat 500', 'Toyota Aygo']),
    h1: makeH1('155/65 R14'), introText: makeIntro('155/65 R14', CATEGORY_KLEINWAGEN, ['VW Up', 'Skoda Citigo', 'Seat Mii', 'Fiat 500']),
  },
  {
    slug: '165-70-r14',
    width: 165, aspectRatio: 70, rimDiameter: 14,
    displayName: '165/70 R14',
    category: CATEGORY_KLEINWAGEN,
    commonVehicles: ['Dacia Sandero', 'Renault Clio', 'Fiat Punto', 'Ford Ka'],
    speedIndices: ['T', 'H'], loadIndices: ['81'],
    seasonTip: 'Wegen des höheren Profils gut für nasse Straßen geeignet. Winterreifen empfohlen in Regionen mit Schnee.',
    monthlySearchVolume: 3500,
    metaTitle: makeTitle('165/70 R14'), metaDescription: makeDescription('165/70 R14', ['Dacia Sandero', 'Renault Clio', 'Fiat Punto']),
    h1: makeH1('165/70 R14'), introText: makeIntro('165/70 R14', CATEGORY_KLEINWAGEN, ['Dacia Sandero', 'Renault Clio', 'Fiat Punto', 'Ford Ka']),
  },
  {
    slug: '175-65-r14',
    width: 175, aspectRatio: 65, rimDiameter: 14,
    displayName: '175/65 R14',
    category: CATEGORY_KLEINWAGEN,
    commonVehicles: ['VW Polo', 'Opel Corsa', 'Renault Clio', 'Ford Fiesta', 'Skoda Fabia'],
    speedIndices: ['T', 'H'], loadIndices: ['82', '86'],
    seasonTip: 'Klassische Kleinwagengröße – Ganzjahresreifen für moderate Klimazonen geeignet, in Bergregionen separate Saisonreifen wählen.',
    monthlySearchVolume: 8200,
    metaTitle: makeTitle('175/65 R14'), metaDescription: makeDescription('175/65 R14', ['VW Polo', 'Opel Corsa', 'Ford Fiesta']),
    h1: makeH1('175/65 R14'), introText: makeIntro('175/65 R14', CATEGORY_KLEINWAGEN, ['VW Polo', 'Opel Corsa', 'Renault Clio', 'Ford Fiesta']),
  },
  {
    slug: '175-65-r15',
    width: 175, aspectRatio: 65, rimDiameter: 15,
    displayName: '175/65 R15',
    category: CATEGORY_KLEINWAGEN,
    commonVehicles: ['Toyota Yaris', 'Honda Jazz', 'Mazda 2', 'Suzuki Swift'],
    speedIndices: ['H', 'T'], loadIndices: ['84'],
    seasonTip: 'Gute Allroundgröße für Kleinwagen mit 15-Zoll-Felgen. Winterreifen für Sicherheit im Winter empfohlen.',
    monthlySearchVolume: 3200,
    metaTitle: makeTitle('175/65 R15'), metaDescription: makeDescription('175/65 R15', ['Toyota Yaris', 'Honda Jazz', 'Mazda 2']),
    h1: makeH1('175/65 R15'), introText: makeIntro('175/65 R15', CATEGORY_KLEINWAGEN, ['Toyota Yaris', 'Honda Jazz', 'Mazda 2', 'Suzuki Swift']),
  },
  {
    slug: '185-60-r15',
    width: 185, aspectRatio: 60, rimDiameter: 15,
    displayName: '185/60 R15',
    category: CATEGORY_KLEINWAGEN,
    commonVehicles: ['VW Polo', 'Seat Ibiza', 'Skoda Fabia', 'Opel Corsa E', 'Hyundai i20'],
    speedIndices: ['H', 'V'], loadIndices: ['84', '88'],
    seasonTip: 'Sportlichere Kleinwagengröße. Für Vielfahrer lohnen sich separate Sommer- und Winterreifen für optimale Performance.',
    monthlySearchVolume: 6800,
    metaTitle: makeTitle('185/60 R15'), metaDescription: makeDescription('185/60 R15', ['VW Polo', 'Seat Ibiza', 'Opel Corsa']),
    h1: makeH1('185/60 R15'), introText: makeIntro('185/60 R15', CATEGORY_KLEINWAGEN, ['VW Polo', 'Seat Ibiza', 'Skoda Fabia', 'Opel Corsa E']),
  },
  {
    slug: '185-65-r15',
    width: 185, aspectRatio: 65, rimDiameter: 15,
    displayName: '185/65 R15',
    category: CATEGORY_KOMPAKT,
    commonVehicles: ['VW Golf IV', 'Opel Astra G', 'Toyota Corolla', 'Renault Mégane', 'Honda Civic'],
    speedIndices: ['T', 'H', 'V'], loadIndices: ['88', '92'],
    seasonTip: 'Bewährte Allroundgröße – ideal für gemischte Fahrprofile. Bei Jahresfahrleistung über 15.000 km separate Saisonreifen empfohlen.',
    monthlySearchVolume: 9500,
    metaTitle: makeTitle('185/65 R15'), metaDescription: makeDescription('185/65 R15', ['VW Golf', 'Opel Astra', 'Toyota Corolla']),
    h1: makeH1('185/65 R15'), introText: makeIntro('185/65 R15', CATEGORY_KOMPAKT, ['VW Golf IV', 'Opel Astra G', 'Toyota Corolla', 'Renault Mégane']),
  },

  // === KOMPAKTKLASSE ===
  {
    slug: '195-55-r16',
    width: 195, aspectRatio: 55, rimDiameter: 16,
    displayName: '195/55 R16',
    category: CATEGORY_KOMPAKT,
    commonVehicles: ['VW Golf VII', 'Seat Leon', 'Skoda Octavia', 'Renault Mégane IV'],
    speedIndices: ['H', 'V', 'W'], loadIndices: ['87', '91'],
    seasonTip: 'Häufige Kompaktklasse-Größe. Für optimale Sicherheit separate Winter- und Sommerreifen wählen.',
    monthlySearchVolume: 7500,
    metaTitle: makeTitle('195/55 R16'), metaDescription: makeDescription('195/55 R16', ['VW Golf', 'Seat Leon', 'Skoda Octavia']),
    h1: makeH1('195/55 R16'), introText: makeIntro('195/55 R16', CATEGORY_KOMPAKT, ['VW Golf VII', 'Seat Leon', 'Skoda Octavia', 'Renault Mégane IV']),
  },
  {
    slug: '195-65-r15',
    width: 195, aspectRatio: 65, rimDiameter: 15,
    displayName: '195/65 R15',
    category: CATEGORY_KOMPAKT,
    commonVehicles: ['VW Golf', 'Opel Astra', 'Ford Focus', 'Toyota Corolla', 'Skoda Octavia', 'Hyundai i30'],
    speedIndices: ['T', 'H', 'V'], loadIndices: ['91', '95'],
    seasonTip: 'Die meistverkaufte Reifengröße Europas. Riesige Auswahl an Sommer-, Winter- und Ganzjahresreifen in allen Preisklassen verfügbar.',
    monthlySearchVolume: 18000,
    metaTitle: makeTitle('195/65 R15'), metaDescription: makeDescription('195/65 R15', ['VW Golf', 'Opel Astra', 'Ford Focus']),
    h1: makeH1('195/65 R15'), introText: makeIntro('195/65 R15', CATEGORY_KOMPAKT, ['VW Golf', 'Opel Astra', 'Ford Focus', 'Toyota Corolla']),
  },
  {
    slug: '205-55-r16',
    width: 205, aspectRatio: 55, rimDiameter: 16,
    displayName: '205/55 R16',
    category: CATEGORY_KOMPAKT,
    commonVehicles: ['VW Golf', 'Audi A3', 'BMW 1er', 'Mercedes A-Klasse', 'Skoda Octavia', 'Seat Leon'],
    speedIndices: ['H', 'V', 'W'], loadIndices: ['91', '94'],
    seasonTip: 'Die beliebteste Reifengröße Deutschlands! Extrem große Auswahl. Premium-Marken wie Continental, Michelin und Goodyear bieten hier Top-Modelle.',
    monthlySearchVolume: 40000,
    metaTitle: makeTitle('205/55 R16'), metaDescription: makeDescription('205/55 R16', ['VW Golf', 'Audi A3', 'BMW 1er']),
    h1: makeH1('205/55 R16'), introText: makeIntro('205/55 R16', CATEGORY_KOMPAKT, ['VW Golf', 'Audi A3', 'BMW 1er', 'Mercedes A-Klasse']),
  },
  {
    slug: '205-55-r17',
    width: 205, aspectRatio: 55, rimDiameter: 17,
    displayName: '205/55 R17',
    category: CATEGORY_KOMPAKT,
    commonVehicles: ['VW Golf VIII', 'Audi A3 Sportback', 'Seat Leon IV', 'Cupra Born'],
    speedIndices: ['V', 'W', 'Y'], loadIndices: ['91', '95'],
    seasonTip: 'Moderne Kompaktklasse-Größe für 17-Zoll-Felgen. Sportliche Auslegung mit gutem Nassgriff.',
    monthlySearchVolume: 6500,
    metaTitle: makeTitle('205/55 R17'), metaDescription: makeDescription('205/55 R17', ['VW Golf VIII', 'Audi A3', 'Seat Leon']),
    h1: makeH1('205/55 R17'), introText: makeIntro('205/55 R17', CATEGORY_KOMPAKT, ['VW Golf VIII', 'Audi A3 Sportback', 'Seat Leon IV', 'Cupra Born']),
  },
  {
    slug: '205-60-r16',
    width: 205, aspectRatio: 60, rimDiameter: 16,
    displayName: '205/60 R16',
    category: CATEGORY_KOMPAKT,
    commonVehicles: ['VW Tiguan', 'Toyota RAV4', 'Opel Mokka', 'Kia Sportage', 'Hyundai Tucson'],
    speedIndices: ['H', 'V', 'W'], loadIndices: ['92', '96'],
    seasonTip: 'Vielseitige Größe für Kompakt-SUVs. Winterreifen besonders wichtig wegen höherem Fahrzeuggewicht.',
    monthlySearchVolume: 12000,
    metaTitle: makeTitle('205/60 R16'), metaDescription: makeDescription('205/60 R16', ['VW Tiguan', 'Toyota RAV4', 'Kia Sportage']),
    h1: makeH1('205/60 R16'), introText: makeIntro('205/60 R16', CATEGORY_KOMPAKT, ['VW Tiguan', 'Toyota RAV4', 'Opel Mokka', 'Kia Sportage']),
  },

  // === MITTELKLASSE ===
  {
    slug: '215-55-r17',
    width: 215, aspectRatio: 55, rimDiameter: 17,
    displayName: '215/55 R17',
    category: CATEGORY_MITTELKLASSE,
    commonVehicles: ['VW Passat', 'Skoda Superb', 'Ford Mondeo', 'Mazda 6', 'Toyota Camry'],
    speedIndices: ['V', 'W'], loadIndices: ['94', '98'],
    seasonTip: 'Ideal für Mittelklasse-Limousinen und Kombis. Bei Langstreckenfahrern separate Saisonreifen für optimalen Komfort.',
    monthlySearchVolume: 9000,
    metaTitle: makeTitle('215/55 R17'), metaDescription: makeDescription('215/55 R17', ['VW Passat', 'Skoda Superb', 'Ford Mondeo']),
    h1: makeH1('215/55 R17'), introText: makeIntro('215/55 R17', CATEGORY_MITTELKLASSE, ['VW Passat', 'Skoda Superb', 'Ford Mondeo', 'Mazda 6']),
  },
  {
    slug: '215-60-r17',
    width: 215, aspectRatio: 60, rimDiameter: 17,
    displayName: '215/60 R17',
    category: CATEGORY_SUV,
    commonVehicles: ['VW Tiguan', 'Hyundai Tucson', 'Kia Sportage', 'Nissan Qashqai', 'Mazda CX-5'],
    speedIndices: ['H', 'V'], loadIndices: ['96', '100'],
    seasonTip: 'Beliebte SUV-Standardgröße. M+S-Winterreifen für schwere Fahrzeuge besonders sicherheitsrelevant.',
    monthlySearchVolume: 7000,
    metaTitle: makeTitle('215/60 R17'), metaDescription: makeDescription('215/60 R17', ['VW Tiguan', 'Hyundai Tucson', 'Nissan Qashqai']),
    h1: makeH1('215/60 R17'), introText: makeIntro('215/60 R17', CATEGORY_SUV, ['VW Tiguan', 'Hyundai Tucson', 'Kia Sportage', 'Nissan Qashqai']),
  },
  {
    slug: '215-65-r16',
    width: 215, aspectRatio: 65, rimDiameter: 16,
    displayName: '215/65 R16',
    category: CATEGORY_SUV,
    commonVehicles: ['VW Tiguan', 'Dacia Duster', 'Jeep Renegade', 'Renault Kadjar', 'Suzuki Vitara'],
    speedIndices: ['H', 'T'], loadIndices: ['98', '102'],
    seasonTip: 'SUV-Größe mit hohem Komfortprofil. Ganzjahresreifen mit SUV-Kennzeichnung für moderate Klimazonen eine gute Option.',
    monthlySearchVolume: 7200,
    metaTitle: makeTitle('215/65 R16'), metaDescription: makeDescription('215/65 R16', ['VW Tiguan', 'Dacia Duster', 'Jeep Renegade']),
    h1: makeH1('215/65 R16'), introText: makeIntro('215/65 R16', CATEGORY_SUV, ['VW Tiguan', 'Dacia Duster', 'Jeep Renegade', 'Renault Kadjar']),
  },
  {
    slug: '225-40-r18',
    width: 225, aspectRatio: 40, rimDiameter: 18,
    displayName: '225/40 R18',
    category: CATEGORY_SPORT,
    commonVehicles: ['BMW 3er', 'Mercedes C-Klasse', 'Audi A4', 'VW Golf GTI', 'Cupra Formentor'],
    speedIndices: ['W', 'Y'], loadIndices: ['88', '92'],
    seasonTip: 'Sportliche Größe mit niedrigem Querschnitt. Hochwertige Sommerreifen für beste Performance, im Winter auf wettertaugliche Bereifung achten.',
    monthlySearchVolume: 15000,
    metaTitle: makeTitle('225/40 R18'), metaDescription: makeDescription('225/40 R18', ['BMW 3er', 'Mercedes C-Klasse', 'VW Golf GTI']),
    h1: makeH1('225/40 R18'), introText: makeIntro('225/40 R18', CATEGORY_SPORT, ['BMW 3er', 'Mercedes C-Klasse', 'Audi A4', 'VW Golf GTI']),
  },
  {
    slug: '225-45-r17',
    width: 225, aspectRatio: 45, rimDiameter: 17,
    displayName: '225/45 R17',
    category: CATEGORY_MITTELKLASSE,
    commonVehicles: ['BMW 3er', 'Audi A4', 'Mercedes C-Klasse', 'VW Passat', 'Skoda Superb', 'Mazda 6'],
    speedIndices: ['V', 'W', 'Y'], loadIndices: ['91', '94'],
    seasonTip: 'Premium-Mittelklasse-Größe mit riesiger Markenauswahl. Continental PremiumContact, Michelin Primacy und Goodyear Eagle besonders empfohlen.',
    monthlySearchVolume: 22000,
    metaTitle: makeTitle('225/45 R17'), metaDescription: makeDescription('225/45 R17', ['BMW 3er', 'Audi A4', 'Mercedes C-Klasse']),
    h1: makeH1('225/45 R17'), introText: makeIntro('225/45 R17', CATEGORY_MITTELKLASSE, ['BMW 3er', 'Audi A4', 'Mercedes C-Klasse', 'VW Passat']),
  },
  {
    slug: '225-45-r18',
    width: 225, aspectRatio: 45, rimDiameter: 18,
    displayName: '225/45 R18',
    category: CATEGORY_MITTELKLASSE,
    commonVehicles: ['BMW 3er', 'Audi A4', 'Mercedes C-Klasse', 'VW Arteon', 'Peugeot 508'],
    speedIndices: ['W', 'Y'], loadIndices: ['91', '95'],
    seasonTip: 'Premium-Größe für sportliche Mittelklasse. Run-Flat-Varianten für BMW und Mercedes verfügbar.',
    monthlySearchVolume: 10000,
    metaTitle: makeTitle('225/45 R18'), metaDescription: makeDescription('225/45 R18', ['BMW 3er', 'Audi A4', 'Mercedes C-Klasse']),
    h1: makeH1('225/45 R18'), introText: makeIntro('225/45 R18', CATEGORY_MITTELKLASSE, ['BMW 3er', 'Audi A4', 'Mercedes C-Klasse', 'VW Arteon']),
  },
  {
    slug: '225-50-r17',
    width: 225, aspectRatio: 50, rimDiameter: 17,
    displayName: '225/50 R17',
    category: CATEGORY_MITTELKLASSE,
    commonVehicles: ['VW Passat', 'Skoda Superb', 'Audi A4 Avant', 'Mercedes C-Klasse T-Modell'],
    speedIndices: ['V', 'W'], loadIndices: ['94', '98'],
    seasonTip: 'Komfort-orientierte Mittelklasse-Größe. Sehr gute Auswahl an Ganzjahresreifen verfügbar.',
    monthlySearchVolume: 8000,
    metaTitle: makeTitle('225/50 R17'), metaDescription: makeDescription('225/50 R17', ['VW Passat', 'Skoda Superb', 'Audi A4']),
    h1: makeH1('225/50 R17'), introText: makeIntro('225/50 R17', CATEGORY_MITTELKLASSE, ['VW Passat', 'Skoda Superb', 'Audi A4 Avant', 'Mercedes C-Klasse T-Modell']),
  },
  {
    slug: '225-55-r17',
    width: 225, aspectRatio: 55, rimDiameter: 17,
    displayName: '225/55 R17',
    category: CATEGORY_MITTELKLASSE,
    commonVehicles: ['Mercedes E-Klasse', 'BMW 5er', 'Audi A6', 'VW Passat Alltrack'],
    speedIndices: ['V', 'W'], loadIndices: ['97', '101'],
    seasonTip: 'Obere Mittelklasse-Größe mit Fokus auf Komfort. Premiumreifen für Langstreckenkomfort empfohlen.',
    monthlySearchVolume: 6000,
    metaTitle: makeTitle('225/55 R17'), metaDescription: makeDescription('225/55 R17', ['Mercedes E-Klasse', 'BMW 5er', 'Audi A6']),
    h1: makeH1('225/55 R17'), introText: makeIntro('225/55 R17', CATEGORY_MITTELKLASSE, ['Mercedes E-Klasse', 'BMW 5er', 'Audi A6', 'VW Passat Alltrack']),
  },
  {
    slug: '225-55-r18',
    width: 225, aspectRatio: 55, rimDiameter: 18,
    displayName: '225/55 R18',
    category: CATEGORY_SUV,
    commonVehicles: ['VW Tiguan', 'Audi Q3', 'BMW X1', 'Mercedes GLA', 'Volvo XC40'],
    speedIndices: ['V', 'W'], loadIndices: ['98', '102'],
    seasonTip: 'Premium-SUV-Größe. Achte auf SUV-spezifische Reifenmodelle für das höhere Fahrzeuggewicht.',
    monthlySearchVolume: 5500,
    metaTitle: makeTitle('225/55 R18'), metaDescription: makeDescription('225/55 R18', ['VW Tiguan', 'Audi Q3', 'BMW X1']),
    h1: makeH1('225/55 R18'), introText: makeIntro('225/55 R18', CATEGORY_SUV, ['VW Tiguan', 'Audi Q3', 'BMW X1', 'Mercedes GLA']),
  },
  {
    slug: '225-65-r17',
    width: 225, aspectRatio: 65, rimDiameter: 17,
    displayName: '225/65 R17',
    category: CATEGORY_SUV,
    commonVehicles: ['Toyota RAV4', 'Honda CR-V', 'Mazda CX-5', 'Subaru Forester', 'Kia Sportage'],
    speedIndices: ['H', 'V'], loadIndices: ['102', '106'],
    seasonTip: 'Standard-SUV-Größe mit hohem Komfort. M+S-Kennzeichnung und 3PMSF-Symbol für Wintertauglichkeit beachten.',
    monthlySearchVolume: 6500,
    metaTitle: makeTitle('225/65 R17'), metaDescription: makeDescription('225/65 R17', ['Toyota RAV4', 'Honda CR-V', 'Mazda CX-5']),
    h1: makeH1('225/65 R17'), introText: makeIntro('225/65 R17', CATEGORY_SUV, ['Toyota RAV4', 'Honda CR-V', 'Mazda CX-5', 'Subaru Forester']),
  },

  // === PREMIUM / OBERKLASSE ===
  {
    slug: '235-40-r18',
    width: 235, aspectRatio: 40, rimDiameter: 18,
    displayName: '235/40 R18',
    category: CATEGORY_SPORT,
    commonVehicles: ['BMW 3er', 'Audi S4', 'Mercedes-AMG C43', 'VW Golf R', 'Porsche Boxster'],
    speedIndices: ['W', 'Y'], loadIndices: ['91', '95'],
    seasonTip: 'Performance-Größe – hochwertige UHP-Reifen empfohlen. Im Winter auf Performance-Winterreifen mit Y-Index achten.',
    monthlySearchVolume: 5000,
    metaTitle: makeTitle('235/40 R18'), metaDescription: makeDescription('235/40 R18', ['BMW 3er', 'Audi S4', 'Mercedes-AMG C43']),
    h1: makeH1('235/40 R18'), introText: makeIntro('235/40 R18', CATEGORY_SPORT, ['BMW 3er', 'Audi S4', 'Mercedes-AMG C43', 'VW Golf R']),
  },
  {
    slug: '235-40-r19',
    width: 235, aspectRatio: 40, rimDiameter: 19,
    displayName: '235/40 R19',
    category: CATEGORY_SPORT,
    commonVehicles: ['BMW 4er', 'Audi A5 Sportback', 'Mercedes C-Klasse Coupé', 'Kia Stinger'],
    speedIndices: ['W', 'Y'], loadIndices: ['92', '96'],
    seasonTip: 'Große Performance-Größe. Run-Flat-Optionen für BMW und Mini verfügbar.',
    monthlySearchVolume: 4000,
    metaTitle: makeTitle('235/40 R19'), metaDescription: makeDescription('235/40 R19', ['BMW 4er', 'Audi A5', 'Mercedes C-Klasse Coupé']),
    h1: makeH1('235/40 R19'), introText: makeIntro('235/40 R19', CATEGORY_SPORT, ['BMW 4er', 'Audi A5 Sportback', 'Mercedes C-Klasse Coupé', 'Kia Stinger']),
  },
  {
    slug: '235-45-r17',
    width: 235, aspectRatio: 45, rimDiameter: 17,
    displayName: '235/45 R17',
    category: CATEGORY_MITTELKLASSE,
    commonVehicles: ['BMW 3er', 'Audi A4', 'Mercedes C-Klasse', 'Toyota Supra', 'Subaru BRZ'],
    speedIndices: ['V', 'W', 'Y'], loadIndices: ['94', '97'],
    seasonTip: 'Sportlich-komfortable Größe für Limousinen. Breites Angebot an Premium- und Budget-Reifen.',
    monthlySearchVolume: 5500,
    metaTitle: makeTitle('235/45 R17'), metaDescription: makeDescription('235/45 R17', ['BMW 3er', 'Audi A4', 'Mercedes C-Klasse']),
    h1: makeH1('235/45 R17'), introText: makeIntro('235/45 R17', CATEGORY_MITTELKLASSE, ['BMW 3er', 'Audi A4', 'Mercedes C-Klasse', 'Toyota Supra']),
  },
  {
    slug: '235-45-r18',
    width: 235, aspectRatio: 45, rimDiameter: 18,
    displayName: '235/45 R18',
    category: CATEGORY_MITTELKLASSE,
    commonVehicles: ['BMW 5er', 'Mercedes E-Klasse', 'Audi A6', 'Volvo S60', 'Lexus IS'],
    speedIndices: ['W', 'Y'], loadIndices: ['94', '98'],
    seasonTip: 'Oberklasse-Größe mit sportlicher Auslegung. Premium-Reifen für Langlebigkeit und Laufruhe empfohlen.',
    monthlySearchVolume: 7500,
    metaTitle: makeTitle('235/45 R18'), metaDescription: makeDescription('235/45 R18', ['BMW 5er', 'Mercedes E-Klasse', 'Audi A6']),
    h1: makeH1('235/45 R18'), introText: makeIntro('235/45 R18', CATEGORY_MITTELKLASSE, ['BMW 5er', 'Mercedes E-Klasse', 'Audi A6', 'Volvo S60']),
  },
  {
    slug: '235-50-r18',
    width: 235, aspectRatio: 50, rimDiameter: 18,
    displayName: '235/50 R18',
    category: CATEGORY_SUV,
    commonVehicles: ['Audi Q5', 'BMW X3', 'Mercedes GLC', 'Volvo XC60', 'Porsche Macan'],
    speedIndices: ['V', 'W'], loadIndices: ['97', '101'],
    seasonTip: 'Premium-SUV-Größe für mittelgroße Premium-SUVs. Auf XL-Tragfähigkeit achten.',
    monthlySearchVolume: 5000,
    metaTitle: makeTitle('235/50 R18'), metaDescription: makeDescription('235/50 R18', ['Audi Q5', 'BMW X3', 'Mercedes GLC']),
    h1: makeH1('235/50 R18'), introText: makeIntro('235/50 R18', CATEGORY_SUV, ['Audi Q5', 'BMW X3', 'Mercedes GLC', 'Volvo XC60']),
  },
  {
    slug: '235-55-r17',
    width: 235, aspectRatio: 55, rimDiameter: 17,
    displayName: '235/55 R17',
    category: CATEGORY_SUV,
    commonVehicles: ['VW Tiguan Allspace', 'Ford Edge', 'Hyundai Santa Fe', 'Kia Sorento'],
    speedIndices: ['V', 'W'], loadIndices: ['99', '103'],
    seasonTip: 'Komfortgröße für größere SUVs. Bei schweren Fahrzeugen auf ausreichenden Lastindex achten.',
    monthlySearchVolume: 4500,
    metaTitle: makeTitle('235/55 R17'), metaDescription: makeDescription('235/55 R17', ['VW Tiguan Allspace', 'Ford Edge', 'Hyundai Santa Fe']),
    h1: makeH1('235/55 R17'), introText: makeIntro('235/55 R17', CATEGORY_SUV, ['VW Tiguan Allspace', 'Ford Edge', 'Hyundai Santa Fe', 'Kia Sorento']),
  },
  {
    slug: '235-55-r18',
    width: 235, aspectRatio: 55, rimDiameter: 18,
    displayName: '235/55 R18',
    category: CATEGORY_SUV,
    commonVehicles: ['Audi Q5', 'BMW X3', 'Mercedes GLC', 'Volvo XC60', 'Toyota Highlander'],
    speedIndices: ['V', 'W'], loadIndices: ['100', '104'],
    seasonTip: 'SUV-Standardgröße für gehobene Ansprüche. Premiumreifen wie Michelin CrossClimate SUV bieten exzellente Allroundeigenschaften.',
    monthlySearchVolume: 5500,
    metaTitle: makeTitle('235/55 R18'), metaDescription: makeDescription('235/55 R18', ['Audi Q5', 'BMW X3', 'Mercedes GLC']),
    h1: makeH1('235/55 R18'), introText: makeIntro('235/55 R18', CATEGORY_SUV, ['Audi Q5', 'BMW X3', 'Mercedes GLC', 'Volvo XC60']),
  },
  {
    slug: '235-55-r19',
    width: 235, aspectRatio: 55, rimDiameter: 19,
    displayName: '235/55 R19',
    category: CATEGORY_SUV,
    commonVehicles: ['BMW X3', 'Mercedes GLC', 'Audi Q5', 'Volvo XC60', 'Range Rover Evoque'],
    speedIndices: ['V', 'W', 'Y'], loadIndices: ['101', '105'],
    seasonTip: 'Premium-SUV-Größe mit 19-Zoll-Felgen. Hochwertige Reifen für beste Performance und Langlebigkeit.',
    monthlySearchVolume: 8000,
    metaTitle: makeTitle('235/55 R19'), metaDescription: makeDescription('235/55 R19', ['BMW X3', 'Mercedes GLC', 'Range Rover Evoque']),
    h1: makeH1('235/55 R19'), introText: makeIntro('235/55 R19', CATEGORY_SUV, ['BMW X3', 'Mercedes GLC', 'Audi Q5', 'Range Rover Evoque']),
  },
  {
    slug: '245-40-r18',
    width: 245, aspectRatio: 40, rimDiameter: 18,
    displayName: '245/40 R18',
    category: CATEGORY_SPORT,
    commonVehicles: ['BMW 3er', 'Audi S5', 'Mercedes-AMG C43', 'Porsche 718 Cayman'],
    speedIndices: ['W', 'Y'], loadIndices: ['93', '97'],
    seasonTip: 'Hochleistungsgröße – UHP-Reifen für maximalen Grip. Vorsicht bei Nässe mit Sport-Compound.',
    monthlySearchVolume: 5500,
    metaTitle: makeTitle('245/40 R18'), metaDescription: makeDescription('245/40 R18', ['BMW 3er', 'Audi S5', 'Porsche 718 Cayman']),
    h1: makeH1('245/40 R18'), introText: makeIntro('245/40 R18', CATEGORY_SPORT, ['BMW 3er', 'Audi S5', 'Mercedes-AMG C43', 'Porsche 718 Cayman']),
  },
  {
    slug: '245-40-r19',
    width: 245, aspectRatio: 40, rimDiameter: 19,
    displayName: '245/40 R19',
    category: CATEGORY_SPORT,
    commonVehicles: ['BMW 5er', 'Audi A6', 'Mercedes E-Klasse AMG', 'Porsche Taycan'],
    speedIndices: ['W', 'Y'], loadIndices: ['94', '98'],
    seasonTip: 'Performance-Größe für Premium-Limousinen. Auf Noise-Cancelling-Technologie bei Premium-Marken achten.',
    monthlySearchVolume: 4500,
    metaTitle: makeTitle('245/40 R19'), metaDescription: makeDescription('245/40 R19', ['BMW 5er', 'Audi A6', 'Porsche Taycan']),
    h1: makeH1('245/40 R19'), introText: makeIntro('245/40 R19', CATEGORY_SPORT, ['BMW 5er', 'Audi A6', 'Mercedes E-Klasse AMG', 'Porsche Taycan']),
  },
  {
    slug: '245-45-r18',
    width: 245, aspectRatio: 45, rimDiameter: 18,
    displayName: '245/45 R18',
    category: CATEGORY_OBERKLASSE,
    commonVehicles: ['BMW 5er', 'Mercedes E-Klasse', 'Audi A6', 'Jaguar XF', 'Genesis G70'],
    speedIndices: ['W', 'Y'], loadIndices: ['96', '100'],
    seasonTip: 'Oberklasse-Größe. Premium-Reifen wie Continental SportContact und Michelin Pilot Sport empfohlen.',
    monthlySearchVolume: 7000,
    metaTitle: makeTitle('245/45 R18'), metaDescription: makeDescription('245/45 R18', ['BMW 5er', 'Mercedes E-Klasse', 'Audi A6']),
    h1: makeH1('245/45 R18'), introText: makeIntro('245/45 R18', CATEGORY_OBERKLASSE, ['BMW 5er', 'Mercedes E-Klasse', 'Audi A6', 'Jaguar XF']),
  },
  {
    slug: '245-45-r19',
    width: 245, aspectRatio: 45, rimDiameter: 19,
    displayName: '245/45 R19',
    category: CATEGORY_OBERKLASSE,
    commonVehicles: ['BMW 5er', 'Mercedes E-Klasse', 'Audi A7', 'Porsche Taycan'],
    speedIndices: ['W', 'Y'], loadIndices: ['98', '102'],
    seasonTip: 'Sportliche Oberklasse-Größe für 19-Zoll. Auf Laufleistung und Laufruhe bei der Reifenwahl achten.',
    monthlySearchVolume: 5000,
    metaTitle: makeTitle('245/45 R19'), metaDescription: makeDescription('245/45 R19', ['BMW 5er', 'Mercedes E-Klasse', 'Porsche Taycan']),
    h1: makeH1('245/45 R19'), introText: makeIntro('245/45 R19', CATEGORY_OBERKLASSE, ['BMW 5er', 'Mercedes E-Klasse', 'Audi A7', 'Porsche Taycan']),
  },
  {
    slug: '245-45-r20',
    width: 245, aspectRatio: 45, rimDiameter: 20,
    displayName: '245/45 R20',
    category: CATEGORY_SUV,
    commonVehicles: ['BMW X5', 'Mercedes GLE', 'Audi Q7', 'Volvo XC90', 'Porsche Cayenne'],
    speedIndices: ['W', 'Y'], loadIndices: ['99', '103'],
    seasonTip: 'Große SUV-Größe für Premium-Fahrzeuge. XL-Ausführung für schwere SUVs dringend empfohlen.',
    monthlySearchVolume: 4000,
    metaTitle: makeTitle('245/45 R20'), metaDescription: makeDescription('245/45 R20', ['BMW X5', 'Mercedes GLE', 'Porsche Cayenne']),
    h1: makeH1('245/45 R20'), introText: makeIntro('245/45 R20', CATEGORY_SUV, ['BMW X5', 'Mercedes GLE', 'Audi Q7', 'Porsche Cayenne']),
  },

  // === SUV / GELÄNDEWAGEN ===
  {
    slug: '235-60-r18',
    width: 235, aspectRatio: 60, rimDiameter: 18,
    displayName: '235/60 R18',
    category: CATEGORY_SUV,
    commonVehicles: ['Hyundai Tucson', 'Kia Sportage', 'Ford Kuga', 'Peugeot 3008', 'Citroën C5 Aircross'],
    speedIndices: ['H', 'V', 'W'], loadIndices: ['103', '107'],
    seasonTip: 'Komfort-SUV-Größe für Kompakt-SUVs. Ganzjahresreifen mit SUV-Zulassung eine sinnvolle Option.',
    monthlySearchVolume: 5000,
    metaTitle: makeTitle('235/60 R18'), metaDescription: makeDescription('235/60 R18', ['Hyundai Tucson', 'Kia Sportage', 'Ford Kuga']),
    h1: makeH1('235/60 R18'), introText: makeIntro('235/60 R18', CATEGORY_SUV, ['Hyundai Tucson', 'Kia Sportage', 'Ford Kuga', 'Peugeot 3008']),
  },
  {
    slug: '255-35-r19',
    width: 255, aspectRatio: 35, rimDiameter: 19,
    displayName: '255/35 R19',
    category: CATEGORY_SPORT,
    commonVehicles: ['BMW M3', 'Audi RS4', 'Mercedes-AMG C63', 'Porsche 911', 'Alfa Romeo Giulia QV'],
    speedIndices: ['Y'], loadIndices: ['92', '96'],
    seasonTip: 'Hochleistungs-Dimension für Sportwagen. Semi-Slick für Trackdays, UHP-Reifen für den Alltag.',
    monthlySearchVolume: 5200,
    metaTitle: makeTitle('255/35 R19'), metaDescription: makeDescription('255/35 R19', ['BMW M3', 'Porsche 911', 'Mercedes-AMG C63']),
    h1: makeH1('255/35 R19'), introText: makeIntro('255/35 R19', CATEGORY_SPORT, ['BMW M3', 'Audi RS4', 'Mercedes-AMG C63', 'Porsche 911']),
  },
  {
    slug: '255-40-r19',
    width: 255, aspectRatio: 40, rimDiameter: 19,
    displayName: '255/40 R19',
    category: CATEGORY_SPORT,
    commonVehicles: ['BMW 5er', 'Audi A7', 'Mercedes-AMG E53', 'Porsche Panamera'],
    speedIndices: ['W', 'Y'], loadIndices: ['96', '100'],
    seasonTip: 'Oberklasse-/Sportwagen-Dimension. Bei der Winterreifenwahl auf den Geschwindigkeitsindex achten.',
    monthlySearchVolume: 4200,
    metaTitle: makeTitle('255/40 R19'), metaDescription: makeDescription('255/40 R19', ['BMW 5er', 'Audi A7', 'Porsche Panamera']),
    h1: makeH1('255/40 R19'), introText: makeIntro('255/40 R19', CATEGORY_SPORT, ['BMW 5er', 'Audi A7', 'Mercedes-AMG E53', 'Porsche Panamera']),
  },
  {
    slug: '255-45-r20',
    width: 255, aspectRatio: 45, rimDiameter: 20,
    displayName: '255/45 R20',
    category: CATEGORY_SUV,
    commonVehicles: ['BMW X5', 'Mercedes GLE', 'Audi Q7', 'Range Rover Sport', 'Porsche Cayenne'],
    speedIndices: ['W', 'Y'], loadIndices: ['101', '105'],
    seasonTip: 'Premium-SUV-Dimension für große Fahrzeuge. XL-Version und Run-Flat-Varianten erhältlich.',
    monthlySearchVolume: 3800,
    metaTitle: makeTitle('255/45 R20'), metaDescription: makeDescription('255/45 R20', ['BMW X5', 'Mercedes GLE', 'Porsche Cayenne']),
    h1: makeH1('255/45 R20'), introText: makeIntro('255/45 R20', CATEGORY_SUV, ['BMW X5', 'Mercedes GLE', 'Audi Q7', 'Range Rover Sport']),
  },
  {
    slug: '255-50-r19',
    width: 255, aspectRatio: 50, rimDiameter: 19,
    displayName: '255/50 R19',
    category: CATEGORY_SUV,
    commonVehicles: ['BMW X5', 'Audi Q7', 'Mercedes GLE', 'VW Touareg', 'Porsche Cayenne'],
    speedIndices: ['V', 'W', 'Y'], loadIndices: ['103', '107'],
    seasonTip: 'Standard-Größe für große Premium-SUVs. Breites Angebot an All-Season-SUV-Reifen.',
    monthlySearchVolume: 4500,
    metaTitle: makeTitle('255/50 R19'), metaDescription: makeDescription('255/50 R19', ['BMW X5', 'Audi Q7', 'VW Touareg']),
    h1: makeH1('255/50 R19'), introText: makeIntro('255/50 R19', CATEGORY_SUV, ['BMW X5', 'Audi Q7', 'Mercedes GLE', 'VW Touareg']),
  },
  {
    slug: '255-55-r18',
    width: 255, aspectRatio: 55, rimDiameter: 18,
    displayName: '255/55 R18',
    category: CATEGORY_SUV,
    commonVehicles: ['VW Touareg', 'Audi Q7', 'Mercedes GLE', 'BMW X5', 'Jeep Grand Cherokee'],
    speedIndices: ['V', 'W'], loadIndices: ['105', '109'],
    seasonTip: 'Komfortgröße für große SUVs. Auf maximale Tragfähigkeit achten, XL-Reifen empfohlen.',
    monthlySearchVolume: 3500,
    metaTitle: makeTitle('255/55 R18'), metaDescription: makeDescription('255/55 R18', ['VW Touareg', 'Audi Q7', 'Jeep Grand Cherokee']),
    h1: makeH1('255/55 R18'), introText: makeIntro('255/55 R18', CATEGORY_SUV, ['VW Touareg', 'Audi Q7', 'Mercedes GLE', 'Jeep Grand Cherokee']),
  },
  {
    slug: '265-60-r18',
    width: 265, aspectRatio: 60, rimDiameter: 18,
    displayName: '265/60 R18',
    category: CATEGORY_SUV,
    commonVehicles: ['Toyota Land Cruiser', 'Mitsubishi Pajero', 'Jeep Wrangler', 'Ford Ranger'],
    speedIndices: ['H', 'T', 'V'], loadIndices: ['110', '114'],
    seasonTip: 'Offroad-fähige SUV-Größe. AT-Reifen (All-Terrain) für Gelände- und Straßennutzung ideal.',
    monthlySearchVolume: 3200,
    metaTitle: makeTitle('265/60 R18'), metaDescription: makeDescription('265/60 R18', ['Toyota Land Cruiser', 'Jeep Wrangler', 'Ford Ranger']),
    h1: makeH1('265/60 R18'), introText: makeIntro('265/60 R18', CATEGORY_SUV, ['Toyota Land Cruiser', 'Mitsubishi Pajero', 'Jeep Wrangler', 'Ford Ranger']),
  },

  // === TRANSPORTER / VAN ===
  {
    slug: '195-65-r16c',
    width: 195, aspectRatio: 65, rimDiameter: 16,
    displayName: '195/65 R16C',
    category: CATEGORY_TRANSPORTER,
    commonVehicles: ['VW Transporter T5/T6', 'Mercedes Vito', 'Ford Transit Custom', 'Opel Vivaro'],
    speedIndices: ['T', 'R'], loadIndices: ['104', '100'],
    seasonTip: 'C-Kennzeichnung für verstärkte Transporterreifen. Ausschließlich Reifen mit C-Kennzeichnung verwenden!',
    monthlySearchVolume: 5500,
    metaTitle: makeTitle('195/65 R16C'), metaDescription: makeDescription('195/65 R16C', ['VW Transporter', 'Mercedes Vito', 'Ford Transit Custom']),
    h1: makeH1('195/65 R16C'), introText: makeIntro('195/65 R16C', CATEGORY_TRANSPORTER, ['VW Transporter T5/T6', 'Mercedes Vito', 'Ford Transit Custom', 'Opel Vivaro']),
  },
  {
    slug: '205-65-r16c',
    width: 205, aspectRatio: 65, rimDiameter: 16,
    displayName: '205/65 R16C',
    category: CATEGORY_TRANSPORTER,
    commonVehicles: ['VW Transporter T6', 'Mercedes Sprinter', 'Ford Transit', 'Fiat Ducato'],
    speedIndices: ['T', 'R'], loadIndices: ['107', '103'],
    seasonTip: 'Verstärkte Transportergröße. Winterreifen für Transporter besonders wichtig bei voller Ladung.',
    monthlySearchVolume: 4500,
    metaTitle: makeTitle('205/65 R16C'), metaDescription: makeDescription('205/65 R16C', ['VW Transporter', 'Mercedes Sprinter', 'Ford Transit']),
    h1: makeH1('205/65 R16C'), introText: makeIntro('205/65 R16C', CATEGORY_TRANSPORTER, ['VW Transporter T6', 'Mercedes Sprinter', 'Ford Transit', 'Fiat Ducato']),
  },
  {
    slug: '215-65-r16c',
    width: 215, aspectRatio: 65, rimDiameter: 16,
    displayName: '215/65 R16C',
    category: CATEGORY_TRANSPORTER,
    commonVehicles: ['Mercedes Sprinter', 'VW Crafter', 'Ford Transit', 'Iveco Daily'],
    speedIndices: ['T', 'R'], loadIndices: ['109', '106'],
    seasonTip: 'Große Transportergröße für Kastenwagen. Auf Tragfähigkeit und C-Kennzeichnung achten.',
    monthlySearchVolume: 3800,
    metaTitle: makeTitle('215/65 R16C'), metaDescription: makeDescription('215/65 R16C', ['Mercedes Sprinter', 'VW Crafter', 'Ford Transit']),
    h1: makeH1('215/65 R16C'), introText: makeIntro('215/65 R16C', CATEGORY_TRANSPORTER, ['Mercedes Sprinter', 'VW Crafter', 'Ford Transit', 'Iveco Daily']),
  },
  {
    slug: '235-65-r16c',
    width: 235, aspectRatio: 65, rimDiameter: 16,
    displayName: '235/65 R16C',
    category: CATEGORY_TRANSPORTER,
    commonVehicles: ['Mercedes Sprinter', 'VW Crafter', 'MAN TGE', 'Fiat Ducato Maxi'],
    speedIndices: ['T', 'R'], loadIndices: ['115', '121'],
    seasonTip: 'Extra-große Transportergröße. Hohe Tragfähigkeit für schwere Nutzfahrzeuge. Regelmäßige Druckkontrolle Pflicht.',
    monthlySearchVolume: 3000,
    metaTitle: makeTitle('235/65 R16C'), metaDescription: makeDescription('235/65 R16C', ['Mercedes Sprinter', 'VW Crafter', 'MAN TGE']),
    h1: makeH1('235/65 R16C'), introText: makeIntro('235/65 R16C', CATEGORY_TRANSPORTER, ['Mercedes Sprinter', 'VW Crafter', 'MAN TGE', 'Fiat Ducato Maxi']),
  },

  // === WEITERE BELIEBTE GRÖSSEN ===
  {
    slug: '185-55-r15',
    width: 185, aspectRatio: 55, rimDiameter: 15,
    displayName: '185/55 R15',
    category: CATEGORY_KLEINWAGEN,
    commonVehicles: ['VW Polo', 'Seat Ibiza', 'Peugeot 208', 'Citroën C3', 'Audi A1'],
    speedIndices: ['H', 'V'], loadIndices: ['82', '86'],
    seasonTip: 'Sportlicher Kleinwagen-Reifen. Im Sommer auf guten Nassgriff achten, im Winter auf kurze Bremswege.',
    monthlySearchVolume: 4500,
    metaTitle: makeTitle('185/55 R15'), metaDescription: makeDescription('185/55 R15', ['VW Polo', 'Seat Ibiza', 'Audi A1']),
    h1: makeH1('185/55 R15'), introText: makeIntro('185/55 R15', CATEGORY_KLEINWAGEN, ['VW Polo', 'Seat Ibiza', 'Peugeot 208', 'Audi A1']),
  },
  {
    slug: '195-60-r16',
    width: 195, aspectRatio: 60, rimDiameter: 16,
    displayName: '195/60 R16',
    category: CATEGORY_KOMPAKT,
    commonVehicles: ['VW Golf Sportsvan', 'Opel Astra K', 'Ford C-Max', 'Renault Scénic'],
    speedIndices: ['H', 'V'], loadIndices: ['89', '93'],
    seasonTip: 'Komfortgröße für Kompaktvans. Ganzjahresreifen bei moderatem Fahrprofil eine sinnvolle Wahl.',
    monthlySearchVolume: 3800,
    metaTitle: makeTitle('195/60 R16'), metaDescription: makeDescription('195/60 R16', ['VW Golf Sportsvan', 'Opel Astra', 'Ford C-Max']),
    h1: makeH1('195/60 R16'), introText: makeIntro('195/60 R16', CATEGORY_KOMPAKT, ['VW Golf Sportsvan', 'Opel Astra K', 'Ford C-Max', 'Renault Scénic']),
  },
  {
    slug: '205-45-r17',
    width: 205, aspectRatio: 45, rimDiameter: 17,
    displayName: '205/45 R17',
    category: CATEGORY_KOMPAKT,
    commonVehicles: ['VW Golf', 'Audi A3', 'Seat Leon', 'BMW 1er', 'Mini Cooper S'],
    speedIndices: ['V', 'W', 'Y'], loadIndices: ['84', '88'],
    seasonTip: 'Sportliche Kompaktklasse-Dimension. Performance-Sommerreifen und wintertaugliche Alternativen verfügbar.',
    monthlySearchVolume: 5000,
    metaTitle: makeTitle('205/45 R17'), metaDescription: makeDescription('205/45 R17', ['VW Golf', 'Audi A3', 'Mini Cooper S']),
    h1: makeH1('205/45 R17'), introText: makeIntro('205/45 R17', CATEGORY_KOMPAKT, ['VW Golf', 'Audi A3', 'Seat Leon', 'Mini Cooper S']),
  },
  {
    slug: '215-45-r17',
    width: 215, aspectRatio: 45, rimDiameter: 17,
    displayName: '215/45 R17',
    category: CATEGORY_KOMPAKT,
    commonVehicles: ['VW Golf GTD', 'Audi A3 Sportback', 'BMW 1er', 'Mercedes A-Klasse', 'Seat Leon FR'],
    speedIndices: ['V', 'W', 'Y'], loadIndices: ['87', '91'],
    seasonTip: 'Sportlich-dynamische Größe für die gehobene Kompaktklasse. W- und Y-Reifen für sportliche Fahrer.',
    monthlySearchVolume: 4200,
    metaTitle: makeTitle('215/45 R17'), metaDescription: makeDescription('215/45 R17', ['VW Golf GTD', 'BMW 1er', 'Mercedes A-Klasse']),
    h1: makeH1('215/45 R17'), introText: makeIntro('215/45 R17', CATEGORY_KOMPAKT, ['VW Golf GTD', 'Audi A3 Sportback', 'BMW 1er', 'Mercedes A-Klasse']),
  },
  {
    slug: '215-50-r17',
    width: 215, aspectRatio: 50, rimDiameter: 17,
    displayName: '215/50 R17',
    category: CATEGORY_MITTELKLASSE,
    commonVehicles: ['VW Passat', 'Opel Insignia', 'Mazda 6', 'Toyota Camry', 'Hyundai Sonata'],
    speedIndices: ['V', 'W'], loadIndices: ['91', '95'],
    seasonTip: 'Ausgewogene Mittelklasse-Größe. Guter Kompromiss aus Komfort und Sportlichkeit.',
    monthlySearchVolume: 3500,
    metaTitle: makeTitle('215/50 R17'), metaDescription: makeDescription('215/50 R17', ['VW Passat', 'Opel Insignia', 'Mazda 6']),
    h1: makeH1('215/50 R17'), introText: makeIntro('215/50 R17', CATEGORY_MITTELKLASSE, ['VW Passat', 'Opel Insignia', 'Mazda 6', 'Toyota Camry']),
  },
  {
    slug: '225-40-r19',
    width: 225, aspectRatio: 40, rimDiameter: 19,
    displayName: '225/40 R19',
    category: CATEGORY_SPORT,
    commonVehicles: ['BMW 4er', 'Audi A5', 'Mercedes CLA AMG', 'Cupra Formentor VZ'],
    speedIndices: ['W', 'Y'], loadIndices: ['89', '93'],
    seasonTip: 'Flache Sport-Dimension. Achte auf Reifendruckkontrollsystem (RDKS) kompatible Ventile bei der Montage.',
    monthlySearchVolume: 3500,
    metaTitle: makeTitle('225/40 R19'), metaDescription: makeDescription('225/40 R19', ['BMW 4er', 'Audi A5', 'Cupra Formentor']),
    h1: makeH1('225/40 R19'), introText: makeIntro('225/40 R19', CATEGORY_SPORT, ['BMW 4er', 'Audi A5', 'Mercedes CLA AMG', 'Cupra Formentor VZ']),
  },
  {
    slug: '245-35-r20',
    width: 245, aspectRatio: 35, rimDiameter: 20,
    displayName: '245/35 R20',
    category: CATEGORY_SPORT,
    commonVehicles: ['BMW M4', 'Audi RS5', 'Mercedes-AMG E63', 'Porsche Panamera', 'Tesla Model S'],
    speedIndices: ['Y'], loadIndices: ['91', '95'],
    seasonTip: 'Extreme Performance-Größe. Nur Premium-UHP-Reifen verwenden für sichere Hochgeschwindigkeitsfahrten.',
    monthlySearchVolume: 3000,
    metaTitle: makeTitle('245/35 R20'), metaDescription: makeDescription('245/35 R20', ['BMW M4', 'Porsche Panamera', 'Tesla Model S']),
    h1: makeH1('245/35 R20'), introText: makeIntro('245/35 R20', CATEGORY_SPORT, ['BMW M4', 'Audi RS5', 'Mercedes-AMG E63', 'Porsche Panamera']),
  },
  {
    slug: '275-40-r20',
    width: 275, aspectRatio: 40, rimDiameter: 20,
    displayName: '275/40 R20',
    category: CATEGORY_SUV,
    commonVehicles: ['BMW X5 M', 'Mercedes-AMG GLE', 'Audi SQ7', 'Porsche Cayenne', 'Range Rover Sport'],
    speedIndices: ['W', 'Y'], loadIndices: ['106'],
    seasonTip: 'Hochleistungs-SUV-Dimension. Premium-Reifen mit verstärkter Seitenwand für schwere Performance-SUVs.',
    monthlySearchVolume: 3200,
    metaTitle: makeTitle('275/40 R20'), metaDescription: makeDescription('275/40 R20', ['BMW X5 M', 'Porsche Cayenne', 'Range Rover Sport']),
    h1: makeH1('275/40 R20'), introText: makeIntro('275/40 R20', CATEGORY_SUV, ['BMW X5 M', 'Mercedes-AMG GLE', 'Audi SQ7', 'Porsche Cayenne']),
  },
  {
    slug: '275-45-r20',
    width: 275, aspectRatio: 45, rimDiameter: 20,
    displayName: '275/45 R20',
    category: CATEGORY_SUV,
    commonVehicles: ['BMW X5', 'Mercedes GLS', 'Audi Q8', 'Range Rover', 'Porsche Cayenne'],
    speedIndices: ['V', 'W', 'Y'], loadIndices: ['110'],
    seasonTip: 'Premium-SUV-Größe. Reifen mit hoher Tragfähigkeit und Komfortauslegung wählen.',
    monthlySearchVolume: 3500,
    metaTitle: makeTitle('275/45 R20'), metaDescription: makeDescription('275/45 R20', ['BMW X5', 'Mercedes GLS', 'Range Rover']),
    h1: makeH1('275/45 R20'), introText: makeIntro('275/45 R20', CATEGORY_SUV, ['BMW X5', 'Mercedes GLS', 'Audi Q8', 'Range Rover']),
  },
  {
    slug: '285-45-r19',
    width: 285, aspectRatio: 45, rimDiameter: 19,
    displayName: '285/45 R19',
    category: CATEGORY_SUV,
    commonVehicles: ['BMW X5', 'VW Touareg', 'Porsche Cayenne', 'Audi Q7', 'Mercedes GLE'],
    speedIndices: ['V', 'W', 'Y'], loadIndices: ['107', '111'],
    seasonTip: 'Extra-breite SUV-Größe. Auf korrekten Reifendruck achten – bei dieser Breite ist Unterdruck besonders gefährlich.',
    monthlySearchVolume: 3000,
    metaTitle: makeTitle('285/45 R19'), metaDescription: makeDescription('285/45 R19', ['BMW X5', 'Porsche Cayenne', 'VW Touareg']),
    h1: makeH1('285/45 R19'), introText: makeIntro('285/45 R19', CATEGORY_SUV, ['BMW X5', 'VW Touareg', 'Porsche Cayenne', 'Audi Q7']),
  },

  // === ELEKTRO-AUTO GRÖSSEN ===
  {
    slug: '235-45-r19',
    width: 235, aspectRatio: 45, rimDiameter: 19,
    displayName: '235/45 R19',
    category: CATEGORY_OBERKLASSE,
    commonVehicles: ['Tesla Model 3', 'BMW i4', 'Polestar 2', 'Hyundai Ioniq 5', 'VW ID.4'],
    speedIndices: ['V', 'W', 'Y'], loadIndices: ['95', '99'],
    seasonTip: 'Beliebte E-Auto-Größe. Reifen mit geringem Rollwiderstand für maximale Reichweite – „EV-Ready"-Modelle bevorzugen.',
    monthlySearchVolume: 5000,
    metaTitle: makeTitle('235/45 R19'), metaDescription: makeDescription('235/45 R19', ['Tesla Model 3', 'BMW i4', 'Hyundai Ioniq 5']),
    h1: makeH1('235/45 R19'), introText: makeIntro('235/45 R19', CATEGORY_OBERKLASSE, ['Tesla Model 3', 'BMW i4', 'Polestar 2', 'Hyundai Ioniq 5']),
  },
  {
    slug: '255-45-r19',
    width: 255, aspectRatio: 45, rimDiameter: 19,
    displayName: '255/45 R19',
    category: CATEGORY_OBERKLASSE,
    commonVehicles: ['Tesla Model Y', 'BMW iX3', 'Mercedes EQC', 'Audi Q4 e-tron', 'Volvo C40'],
    speedIndices: ['V', 'W', 'Y'], loadIndices: ['100', '104'],
    seasonTip: 'E-SUV-Größe mit Fokus auf Reichweite. Leise Reifen (Noise-Cancelling-Technologie) für Elektrofahrzeuge empfohlen.',
    monthlySearchVolume: 3500,
    metaTitle: makeTitle('255/45 R19'), metaDescription: makeDescription('255/45 R19', ['Tesla Model Y', 'BMW iX3', 'Audi Q4 e-tron']),
    h1: makeH1('255/45 R19'), introText: makeIntro('255/45 R19', CATEGORY_OBERKLASSE, ['Tesla Model Y', 'BMW iX3', 'Mercedes EQC', 'Audi Q4 e-tron']),
  },
]

// Helper functions
export function getAllTireSizeSlugs(): string[] {
  return TIRE_SIZES.map(t => t.slug)
}

export function getTireSizeBySlug(slug: string): TireSizeData | undefined {
  return TIRE_SIZES.find(t => t.slug === slug)
}

export function getTireSizesByCategory(category: string): TireSizeData[] {
  return TIRE_SIZES.filter(t => t.category === category)
}

export function getRelatedTireSizes(current: TireSizeData, limit = 6): TireSizeData[] {
  // First try same category, then same rim diameter, then nearby widths
  const sameCategory = TIRE_SIZES.filter(t => t.slug !== current.slug && t.category === current.category)
  const sameRim = TIRE_SIZES.filter(t => t.slug !== current.slug && t.rimDiameter === current.rimDiameter && t.category !== current.category)
  const combined = [...sameCategory, ...sameRim]
  return combined.slice(0, limit)
}

export const TIRE_CATEGORIES = [
  { name: CATEGORY_KLEINWAGEN, icon: '🚗', description: 'Reifen für VW Polo, Opel Corsa, Ford Fiesta & Co.' },
  { name: CATEGORY_KOMPAKT, icon: '🚙', description: 'Reifen für VW Golf, Audi A3, BMW 1er & Co.' },
  { name: CATEGORY_MITTELKLASSE, icon: '🏎️', description: 'Reifen für VW Passat, BMW 3er, Audi A4 & Co.' },
  { name: CATEGORY_OBERKLASSE, icon: '✨', description: 'Reifen für BMW 5er, Mercedes E-Klasse, Audi A6 & Co.' },
  { name: CATEGORY_SUV, icon: '🚜', description: 'Reifen für VW Tiguan, BMW X3, Mercedes GLC & Co.' },
  { name: CATEGORY_SPORT, icon: '🏁', description: 'Reifen für BMW M3, Porsche 911, Mercedes-AMG & Co.' },
  { name: CATEGORY_TRANSPORTER, icon: '🚐', description: 'Reifen für VW Transporter, Mercedes Sprinter & Co.' },
]
